version: "3.9"
services:
  nextjs-app:
    build: .
    container_name: nextjs-container
    ports:
      - "3000:3000" # host:kontener
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
