version: "3.9"
services:
  nextjs-app:
    image: ghcr.io/poewer/mrwhitecv:latest
    container_name: nextjs-container
    ports:
      - "40084:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
